name: GLuaTest Runner

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "master"
      - "dev"

jobs:
  run_tests:
    uses: CFC-Servers/GLuaTest/.github/workflows/run_tests.yml@feature/runner-improvement
    with:
      dockerbuild: true
      gluatest-ref: "feature/runner-improvement"
      requirements: lua/tests/acf/deps.txt
    strategy:
      matrix:
        branch:
          - "live"
          - "x86-64"
      fail-fast: false
